shapegroups = [
    // A  10  S   cocked-S  T  X-over-thumb 
    [ 14, 12, 82, 34,      72, 80],
    // 1  D   X   bent-1 G/Q flat-G alt-G
    [  1, 42, 79, 22,    53, 49,    26],
    // V/2 crvd-V bent-V
    [  77, 41,    88],
    // 8   cocked-8 open-8 25
    [ 10,  32,      66,    13],
    // 5  crvd-5 5-C 5-C-L 5-C-tt
    [  4, 35,    5,  6,    7],
    // B   B-xd flat-B B-L Vulcan crvd-B crvd-flat-B crvd-spread-B bent-B
    [ 20,  19,  46,    18, 92,    36,    37,         39,           23,
      // bent-B-xd bent-B-L
         91,       24],
    // C   sml-C/3 tight-C tight-C/2
    [ 30,  71,     74,     73],
    // O  baby-O flat-O flat-O/2 fanned-flat-O
    [ 65, 21,    51,    50,      45]]

handshapes = [undefined,
	      { shape: '1', id: 1, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1195.gif'},
	      undefined,
	      undefined,
	      { shape: '5', id: 4, group: '5',
	        img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1202.gif'},
	      { shape: '5-C', id: 5, group: '5',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1204.gif'},
	      { shape: '5-C-L', id: 6, group: '5',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1277.gif'},
	      { shape: '5-C-tt', id: 7, group: '5',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1207.gif'},
	      undefined,
	      undefined,
	      { shape: '8', id: 10, group: '8',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1247.gif'},
	      undefined,
	      { shape: '10', id: 12, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1190.gif' },
	      { shape: '25', id: 13, group: '8',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1231.gif'},
	      { shape: 'A', id: 14, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1189.gif' },
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'B-L', id: 18, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1186.gif'},
	      { shape: 'B-xd', id: 19, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1253.gif'},
	      { shape: 'B', id: 20, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1185.gif'},
	      { shape: 'baby-O', id: 21, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1215.gif'},
	      { shape: 'bent-1', id: 22, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1275.gif'},
	      { shape: 'bent-B', id: 23, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1255.gif'},
	      { shape: 'bent-B-L', id: 24, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1256.gif'},
	      undefined,
	      { shape: 'alt-G', id: 26, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1262.gif'},
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'C', id: 30, group: 'C',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1187.gif'},
	      undefined,
	      { shape: 'cocked-8', id: 32, group: '8',
	        img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1234.gif'},
	      undefined,
	      { shape: 'cocked-S', id: 34, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1280.gif'},
	      { shape: 'crvd-5', id: 35, group: '5',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1205.gif'},
	      { shape: 'crvd-B', id: 36, group: 'B',
	        img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1257.gif'},
	      { shape: 'crvd-flat-B', id: 37, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1258.gif'},
	      undefined,
	      { shape: 'crvd-sprd-B', id: 39, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1208.gif'},
	      undefined,
	      { shape: 'crvd-V', id: 41, group: 'V',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1210.gif'},
	      { shape: 'D', id: 42, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1196.gif'},
	      undefined,
	      undefined,
	      { shape: 'fanned-flat-O', id: 45, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1279.gif'},
  	      { shape: 'flat-B', id: 46, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1254.gif'},
	      undefined,
	      undefined,
	      { shape: 'flat-G', id: 49, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1198.gif'},
	      { shape: 'flat-O/2', id: 50, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1223.gif'},
	      { shape: 'flat-O', id: 51, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1213.gif'},
	      undefined,
	      { shape: 'G/Q', id: 53, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1197.gif'},
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'O', id: 65, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1212.gif'},
	      { shape: 'open-8', id: 66, group: '8',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1233.gif'},
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'sml-C/3', id: 71, group: 'C',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1199.gif'},
	      { shape: 'T', id: 72, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1192.gif'},
	      { shape: 'tight-C/2', id: 73, group: 'C',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1222.gif'},
	      { shape: 'tight-C', id: 74, group: 'C',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1214.gif'},
	      undefined,
	      undefined,
	      { shape: 'V/2', id: 77, group: 'V',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1209.gif'},
	      undefined,
	      { shape: 'X', id: 79, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1220.gif'},
	      { shape: 'X-over-thumb', id: 80, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1271.gif'},
	      undefined,
	      { shape: 'S', id: 82, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1191.gif' },
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'bent-V', id: 88, group: 'V',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/bent-v.gif' },
	      undefined,
	      undefined,
	      { shape: 'bent-B-xd', id: 91, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/bent-B-xd.gif'},
	      { shape: 'Vulcan', id: 92, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/Vulcan.gif'},
	     ]

headregions = { 'image': 'images/220px-AlCaponemugshotCPD-vertical.png',
		'width': 107,
		'height': 277,
		'regions': {
		    'ear': {'elt': 'ellipse', 'c': [43, 192],
			      'r': [8, 11], 'xyz': [-2, 4, -2] },
		    'temple': {'elt': 'path', 'xyz': [-2, 5, -1],
			       'd': 'M 53 160 L 68 160 68 177 57 177 z'},
		    'low-temple': {'elt': 'path', 'xyz': [-2, 5, -1],
				   'd': 'M 57 178 L 68 178 68 188 57 188 z'},
		    'forehead': {'elt': 'path', 'xyz': [0, 6],
				 'd': 'M 40 17 L 72 17 72 33 40 33 z' },
		    'R-eye': {'elt': 'ellipse', 'c': [46, 42], 'r': [6, 5],
			      'xyz': [-1, 5]},
		    'L-eye': {'elt': 'ellipse', 'c': [66, 43], 'r': [6, 5],
			      'xyz': [1, 5]},
		    'R-cheek': {'elt': 'ellipse', 'c': [39, 56], 'r': [6, 7],
				'xyz': [-2, 3]},
		    'L-cheek': {'elt': 'ellipse', 'c': [73, 56], 'r': [6, 7],
				'xyz': [2, 3]},
		    'nose':  {'elt': 'ellipse', 'c': [55, 52], 'r': [7, 6],
			      'xyz': [0, 4]},
		    'mouth': {'elt': 'path', 'xyz': [0, 3],
			      'd': 'M 45 61 L 56 59 67 62 67 67 45 67 z' },
		    'chin': {'elt': 'path', 'xyz': [0, 2],
			     'd': 'M 42 71 L 67 71 67 82 42 82 z' }
		}}

bodyregions = { 'image': 'images/Wikiman.svg',
		'width': 200,
		'height': 400,
		'regions': {
		    'neck': {'elt': 'path', 'xyz': [0, 1],
			     'd': 'M 86 68 L 118 68 118 78 86 78 z' },
		    'R-shoulder': {'elt': 'path', 'xyz': [-1, 0],
				   'd': 'M 50 95 L 83 81 83 101 50 101 z' },
		    'L-shoulder': {'elt': 'path', 'xyz': [1, 0],
				   'd': 'M 124 83 L 154 97 156 106 124 106 z' },
		    'chest': {'elt': 'path', 'xyz': [0, 0],
			      'd': 'M 66 108 L 133 108 133 152 66 152 z' },
		    'stomach': {'elt': 'path', 'xyz': [0, -1],
				'd': 'M 66 158 L 136 158 136 186 66 186 z' },
		    'waist': {'elt': 'path', 'xyz': [0, -2],
			      'd': 'M 64 188 L 138 188 140 200 64 200 z' },
		    'thigh': {'elt': 'path', 'xyz': [-1, -3],
			      'd': 'M 64 250 L 100 250 95 275 68 275 z' },
		    'upper-arm': {'elt': 'path', 'xyz': [3, 0],
				  'd': 'M 136 120 L 155 120 155 147 136 148 z'},
		    'elbow': {'elt': 'path', 'xyz': [3, -1],
			      'd': 'M 136 153 L 155 148 162 165 140 170 z' },
		    'arm': {'elt': 'path', 'xyz': [3, -2],
			    'd': 'M 140 171 L 162 166 174 208 158 214 z' },
		    'wrist': {'elt': 'path', 'xyz': [3, -3],
			      'd': 'M 158 215 L 174 209 178 221 164 228 z' },
		    'hand': {'elt': 'path', 'xyz': [3, -4],
			     'd': 'M 164 229 L 178 222 199 235 184 263 172 252 z' },
		}}
		

signs = [{ sign: 'accept',
	   hands: 2,
	   handshape: [ [4, 51], [4, 51] ],
	   position: [ 0, 0 ],
	   palmFace: 'inward',
	   motion: { type: 'straight',
		     dir: [0, 0, -1] },
	   video: 'images/accept.mp4'
	 },
	 { sign: 'alone',
	   hands: 1,
	   handshape: [ [1, 1] ],
	   position: [ 0, 0 ],
	   palmFace: 'inward',
	   motion: { type: 'flat-circle',
		     dir: [0, 0, 0] },
	   //video: 'http://csr.bu.edu/ftp/asl/asllvd/demos/verify_start_end_handshape_annotations/test_auto_move/signs_mov/26_3933_merged.mov'
	   //video: 'images/26_3933_merged.mov'
	   video: 'images/alone.mp4'
	 },
	 { sign: 'blame',
	   hands: 2,
	   handshape: [ [12, 14], [12, 14] ],
	   position: ['chin', 'sightline'],
	   palmFace: 'inward',
	   motion: { type: 'arc',
		     dir: [0, -1, 1] },
	   video: 'images/blame.mp4' },
	 { sign: 'bridge',
	   hands: 1.5,
	   handshape: [ [77, 77], [18, 18] ],
	   position: ['hand', 'elbow'],
	   palmFace: 'toward-palm',
	   motion: { type: 'arc',
		     dir: [0, 1, 0] },
	   video: 'images/bridge.mp4'},
	 { sign: 'good/thank you',
	   hands: 1,
	   handshape: [ [18, 18] ],
	   position: ['chin', 'sightline'],
	   palmFace: 'inward',
	   motion: { type: 'arc',
		     dir: [0, -1, 1] },
	   video: 'images/good-thank-you.mp4'},
	 { sign: 'hello',
	   hands: 1,
	   handshape: [ [20, 20] ],
	   position: ['forehead', [-1, 6, 1]],
	   palmFace: 'outward',
	   motion: { type: 'arc',
		     dir: [-1, 0, 1] },
	   video: 'images/hello.mp4'},
	 { sign: 'not',
	   hands: 1,
	   handshape: [ [12, 12] ],
	   position: ['chin', 'sightline'],
	   palmFace: 'horizontal',
	   motion: { type: 'arc',
		     dir: [0, -1, 1] },
	   video: 'images/not.mp4'},
	 { sign: 'sorry',
	   video: 'images/sorry.mp4',
	   hands: 1,
	   handshape: [ [14, 14] ],
	   position: ['chin', 'sightline'],
	   palmFace: 'inward',
	   motion: { type: 'facing-circle',
		     dir: [0, 0, 0] }}
	]
