shapegroups = [[14, 12, 82, 34, 72, 80],                      // A
	       [1, 42, 79, 22, 53, 49, 26],                   // 1
	       [10, 32, 66, 13],                              // 8
	       [4, 35, 5, 6, 7],                              // 5
	       [20, 19, 46, 18, 92, 36, 37, 39, 23, 91, 24],  // B
	       [30, 71, 74, 73],                              // C
	       [65, 21, 51, 50, 45]]                          // O
handshapes = [undefined,
	      { shape: '1', id: 1, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1195.gif'},
	      undefined,
	      undefined,
	      { shape: '5', id: 4, group: '5',
	        img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1202.gif'},
	      { shape: '5-C', id: 5, group: '5',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1204.gif'},
	      { shape: '5-C-L', id: 6, group: '5',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1277.gif'},
	      { shape: '5-C-tt', id: 7, group: '5',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1207.gif'},
	      undefined,
	      undefined,
	      { shape: '8', id: 10, group: '8',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1247.gif'},
	      undefined,
	      { shape: '10', id: 12, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1190.gif' },
	      { shape: '25', id: 13, group: '8',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1231.gif'},
	      { shape: 'A', id: 14, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1189.gif' },
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'B-L', id: 18, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1186.gif'},
	      { shape: 'B-xd', id: 19, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1253.gif'},
	      { shape: 'B', id: 20, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1185.gif'},
	      { shape: 'baby-O', id: 21, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1215.gif'},
	      { shape: 'bent-1', id: 22, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1275.gif'},
	      { shape: 'bent-B', id: 23, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1255.gif'},
	      { shape: 'bent-B-L', id: 24, group: 'B'
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1256.gif'},
	      undefined,
	      { shape: 'alt-G', id: 26, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1262.gif'},
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'C', id: 30, group: 'C',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1187.gif'},
	      undefined,
	      { shape: 'cocked-8', id: 32, group: '8',
	        img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1234.gif'},
	      undefined,
	      { shape: 'cocked-S', id: 34, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1280.gif'},
	      { shape: 'crvd-5', id: 35, group: '5',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1205.gif'},
	      { shape: 'crvd-B', id: 36, group: 'B',
	        img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1257.gif'},
	      { shape: 'crvd-flat-B', id: 37, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1258.gif'},
	      undefined,
	      { shape: 'crvd-sprd-B', id: 39, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1208.gif'},
	      undefined,
	      undefined,
	      { shape: 'D', id: 42, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1196.gif'},
	      undefined,
	      undefined,
	      { shape: 'fanned-flat-O', id: 45, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1279.gif'},
  	      { shape: 'flat-B', id: 46, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1254.gif'},
	      undefined,
	      undefined,
	      { shape: 'flat-G', id: 49, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1198.gif'},
	      { shape: 'flat-O/2', id: 50, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1223.gif'},
	      { shape: 'flat-O', id: 51, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1213.gif'},
	      undefined,
	      { shape: 'G/Q', id: 53, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1197.gif'},
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'O', id: 65, group: 'O',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1212.gif'},
	      { shape: 'open-8', id: 66, group: '8',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1233.gif'},
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'sml-C/3', id: 71, group: 'C',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1199.gif'},
	      { shape: 'T', id: 72, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1192.gif'},
	      { shape: 'tight-C/2', id: 73, group: 'C',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1222.gif'},
	      { shape: 'tight-C', id: 74, group: 'C',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1214.gif'},
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'X', id: 79, group: '1',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1220.gif'},
	      { shape: 'X-over-thumb', id: 80, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1271.gif'},
	      undefined,
	      { shape: 'S', id: 82, group: 'A',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/_1191.gif' },
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      undefined,
	      { shape: 'bent-B-xd', id: 91, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/bent-B-xd.gif'},
	      { shape: 'Vulcan', id: 92, group: 'B',
		img: 'http://www.bu.edu/asllrp/cslgr/pages/images/Vulcan.gif'},
	     ]

signs = [{ sign: 'alone',
	   hands: 1,
	   handshape: [ [1, 1] ],
	   position: [ 0, 0 ],
	   palmFace: 'inward',
	   motion: { type: 'circle',
		     dir: [0, 0, 0] }},
	 { sign: 'not',
	   hands: 1,
	   handshape: [ [12, 12] ],
	   position: [ ['chin', 'sightline'] ],
	   palmFace: 'toward-palm',
	   motion: { type: 'arc',
		     dir: [0, -1, 1] }}]
